### ISSUE TITLE
All skins appear as Steve

### ISSUE THREAD

**Issue by DirtWith3Ts** [kihira/PlayerRugs#8] opened 2018-06-23 21:39 UTC
I have only player rugs in my 1.7.10 mods folder but i cannot load any skins whatsoever. I have tried killing myself with an anvil, using the /playerrugs command, and /giving myself a skull and crafting the rug with it. No matter what i do, the rug always appears as a steve skin regardless. I am in forge-1.7.10-10.13.4.1614-1.7.10 and have version PlayerRugs-1.7.10-1.1.2 of the mod

**Comment by kihira** [comment] 2018-06-28 14:37
Are you logged in to an account? I think I fixed this for that version but it needs you to be logged in to download the skins from Mojang.

**Comment by RiskyKen** [comment] 2018-06-28 14:50
Mojang turned off `https://s3.amazonaws.com/MinecraftSkins/<player>.png` and `http://skins.minecraft.net/MinecraftSkins/<player>.png` is that not what the issue is?

**Comment by kihira** [comment] 2018-06-28 15:17
Oh Hm, I thought i was using profile code, not directly calling that endpoint. I'll check when I get home tonight

**Comment by kihira** [comment] 2018-07-10 07:35
I'm using profiles code so it should work. Closing this until I can get further information

**Closed as completed by kihira** 2018-07-10 07:35 UTC

**Comment by DirtWith3Ts** [comment] 2018-07-11 15:39
I was in fact logged into the launcher under the account I_AM_DIRT. I could load my own skin. Also, when I tried later without player rugs, but with headcrumbs, other skins loaded fine.
